# Generated by Django 2.2.5 on 2019-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_text_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsche'), ('ES', 'Espanol')], default='DE', max_length=2),
        ),
    ]
