# Generated by Django 2.2.5 on 2019-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190910_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.CharField(choices=[('1', 'Page1'), ('2', 'Page2'), ('3', 'Page2'), ('4', 'Page2'), ('5', 'Page2')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='text',
            name='page',
            field=models.CharField(choices=[('1', 'Page1'), ('2', 'Page2'), ('3', 'Page2'), ('4', 'Page2'), ('5', 'Page2')], default='1', max_length=2),
        ),
    ]
