# Generated by Django 2.2.5 on 2019-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190910_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/<django.db.models.fields.CharField>/', verbose_name=''),
        ),
    ]
