# Generated by Django 2.2.5 on 2019-09-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190910_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='page',
            field=models.CharField(choices=[('Page1', 'Page1'), ('Page2', 'Page2'), ('Page3', 'Page3'), ('Page4', 'Page4'), ('Page5', 'Page5')], default='1', max_length=10),
        ),
    ]
