# Generated by Django 2.2.5 on 2019-09-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190910_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.CharField(choices=[('Menu', 'Menu'), ('Footer', 'Footer'), ('Page1', 'Page1'), ('Page2', 'Page2'), ('Page3', 'Page3'), ('Page4', 'Page4'), ('Page5', 'Page5')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='page',
            field=models.CharField(choices=[('Menu', 'Menu'), ('Footer', 'Footer'), ('Page1', 'Page1'), ('Page2', 'Page2'), ('Page3', 'Page3'), ('Page4', 'Page4'), ('Page5', 'Page5')], default='1', max_length=10),
        ),
    ]
